// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // 마이그레이션은 직접 연결(DIRECT_URL, 5432 포트)을 사용해야 안정적이다.
    // 없으면 DATABASE_URL 로 대체.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
